name: Lint dockerfiles

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint by hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile